### PR TITLE
add help as a base option for tinymce plugins #41

### PR DESCRIPTION
**Pull request by rber474**
Updated from master and recreating changes

### CODE REVIEW

**Comment by stevepiercy** [comment]
@rber474 would you please check the email on you PCA against the email on your GitHub account. Do they match? It is also possible that the person transferring your email from your PCA into the system made a mistake. Can you contact agreements@plone.org to verify?

FWIW, your GitHub account is a member of @plone/developers team.

**Comment by rber474** [comment]
Ohhh global config of email account in company laptop! Sorry guys!

**Comment by rber474** [comment]
@jenkins-plone-org please run jobs

**Comment by rber474** [comment]
Close to fix commits

**Pull request closed without merging**
