### PR TITLE
Add available tinymce plugin `autolink` to the selectable plugins

### PR DESCRIPTION
**Pull request by petschki**
@jensens question: this needs an upgradestep to load the new vocabulary into the registry. Where do I have to put this?

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by jensens — APPROVED** [review]

**Comment by jensens** [comment]
upgrade steps in p.a.upgrade please

**Comment by petschki** [comment]
done here https://github.com/plone/plone.app.upgrade/pull/308

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@petschki Please merge yourself if all branches are ready.

**Pull request merged**
