### PR TITLE
Merge experimental ulocalized time

### PR DESCRIPTION
**Pull request by mauritsvanrees**
This lets `ulocalized_time`: accept a string argument to long_format, for example: `${a} ${d} hello guys ${b} ${Y}`. It is a tiny change, really just one extra if-statement. Fixes https://github.com/plone/Products.CMFPlone/issues/3549.

Also supports dollar signs in registry override for date formats. Then it uses the correct language in multilingual sites. Fixes https://github.com/plone/Products.CMFPlone/issues/3550.

Adds lots of tests for current behavior and for the new fixes/features.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Ready for review. Some unrelated usual suspects in failing robot tests.

**Review by ale-rt — APPROVED** [review]
LGTM

**Comment by ale-rt** [comment]
CC @keul

**Pull request merged**
